baseURL = "https://ethans.space/"
languageCode = "zh-cn"
theme = "hugo-theme-stack"
copyright = "Ethan S. Chen"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[languages.zh-cn]
languageName = "中文"
title = "Ethan S. Chen"
weight = 1

[languages.zh-cn.params.sidebar]
subtitle = "沉舟侧畔千帆过，病树前头万木春"

[languages.en]
languageName = "English"
title = "Ethan S. Chen"
weight = 2

[languages.en.params.sidebar]
subtitle = "Every thing will be ok"

[services.disqus]
shortname = "ethanschen"

[services.googleAnalytics]
id = "G-21Y64E470X"

[pagination]
pagerSize = 5

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
description = "Ethan S. Chen 的个人网站"
mainSections = [ "tech", "life" ]
featuredImageField = "image"
rssFullContent = true
favicon = "https://res.cloudinary.com/dbsadrsxp/image/upload/t_Thumbnail/v1736068974/2025-01-05-%E5%8F%B0%E6%B9%BE%E6%8D%B7%E8%BF%90%E4%B8%AA%E4%BA%BA%E7%85%A7_qtsgsm.jpg"

  [params.footer]
  since = 2_024
  customText = "希望可以一边工作一边旅行✈️"

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "🧑‍💻"
  subtitle = "沉舟侧畔千帆过，病树前头万木春"

    [params.sidebar.avatar]
    enabled = true
    local = false
    src = "https://res.cloudinary.com/dbsadrsxp/image/upload/t_Profile/v1736068974/2025-01-05-%E5%8F%B0%E6%B9%BE%E6%8D%B7%E8%BF%90%E4%B8%AA%E4%BA%BA%E7%85%A7_qtsgsm.jpg"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "disqus"
  disqusjs = { }
  remark42 = { }
  twikoo = { }
  gitalk = { }
  cusdis = { }

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.beaudar]
    issueTerm = "pathname"

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
  [[menu.main]]
  name = "主页"
  url = "/"
  weight = 10
  identifier = "home"
    [menu.main.params]
    icon = "home"
    newTab = false
  [[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 20
  identifier = "archives"
    [menu.main.params]
    icon = "archives"
    newTab = false
  [[menu.main]]
  name = "搜索"
  url = "/search/"
  weight = 30
  identifier = "search"
    [menu.main.params]
    icon = "search"
    newTab = false
  [[menu.main]]
  name = "友链"
  url = "/links/"
  weight = 40
  identifier = "links"
    [menu.main.params]
    icon = "link"
    newTab = false

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/ethanschen"
  weight = 10
    [menu.social.params]
    icon = "brand-github"
  [[menu.social]]
  identifier = "cv"
  name = "CV"
  url = "/personal/cv/"
  weight = 20
    [menu.social.params]
    icon = "file-cv"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
